#define KCN_TIME_NOW		((time_t)-1)
#define KCN_TIME_MININSEC	60
#define KCN_TIME_HOURINSEC	(60 * KCN_TIME_MININSEC)
#define KCN_TIME_DAYINSEC	(24 * KCN_TIME_HOURINSEC)
#define KCN_TIME_JITTER		(5 * KCN_TIME_MININSEC)

